Define the literature review process
elm-community/literature-reviews pull request #4
Opened 2017-05-01 18:58 UTC by opsb

This is loosely based on definition in https://github.com/emberjs/rfcs. I've kept it to a minimum for now so that it can be refined for the Elm community.

2017-05-02 00:27 UTC, mgold requested changes

2017-05-02 00:27 UTC, mgold commented on README.md
> +It's often helpful to get feedback on your concept before getting into the detail required for a literature review. You may open an issue on this repo to start a high-level discussion, with the goal
It seems worth mentioning that elm-discuss and particularly Slack can be good for this.

2017-05-02 00:27 UTC, mgold commented on README.md
> +* If the feature is accepted the PR will be merged.
I think we should go ahead an merge lit reviews that have approval from the community.

2017-05-02 00:27 UTC, mgold commented on README.md
> +* An RFC may be rejected by Evan after public discussion has settled and comments have been made summarizing the rationale for rejection.
* Please don't refer to these documents are RFCs. Although they literally are requests for comments and open discussions, the acronym has the connotation of an approved standard.

* Evan will not (necessarily, likely) review these. Approval comes from the community, separate of implementation.

2017-05-02 01:05 UTC, BrianHicks requested changes
just tweaks :man_dancing:

2017-05-02 01:05 UTC, BrianHicks commented on README.md
> +* Fork the https://github.com/elm-community/literature-reviews
How about `Fork [the elm-community/literature-reviews repo](https://github.com/elm-community/literature-reviews)`?

2017-05-02 01:05 UTC, BrianHicks commented on README.md
> +* Copy TEMPLATE.md to text/my-feature-name.md
Why not `my-feature-name/README.md`? That way, example code and supporting files could live next to the review and GitHub would show a nice overview on the web.

2017-05-02 01:05 UTC, BrianHicks commented on README.md
> +* Eventually, Evan will decide whether the feature is a candidate for inclusion in Elm.
I don't think we should be promising this.

2017-05-02 02:55 UTC, mgold commented on README.md
> +* Copy TEMPLATE.md to text/my-feature-name.md
Oooh, I like that.

2017-05-02 08:52 UTC, opsb commented on README.md
> +* An RFC may be rejected by Evan after public discussion has settled and comments have been made summarizing the rationale for rejection.
copy/paste offence, I was definitely avoiding that

2017-05-02 08:52 UTC, opsb commented on README.md
> +* If the feature is accepted the PR will be merged.
👍

2017-05-02 12:29 UTC, BrianHicks requested changes

2017-05-02 12:29 UTC, BrianHicks commented on README.md
> +* Copy `TEMPLATE.md` to `text/my-feature-name/README.md`
still, why `text`? It's not like this repo will contain thing *other* than literature reviews, right? It's premature namespacing, and if we need it in the future we can always shove them all into a subdirectory.

2017-05-02 12:32 UTC, opsb commented on README.md
> +* Copy `TEMPLATE.md` to `text/my-feature-name/README.md`
Fair enough

2017-05-02 14:55 UTC, mgold approved these changes

2017-05-04 14:15 UTC, BrianHicks approved these changes

2017-05-04 14:19 UTC, merged